spring:
    datasource:
        driver-class-name: org.postgresql.Driver # Habilitar para PostgreSQL
        url: ${BD_URL:jdbc:postgresql://localhost:5432/postgres} # URL de conexi칩n PostgreSQL
        username: ${BD_USER:postgres} # Usuario de la base de datos
        password: ${BD_PASSWORD:123456} # Contrase침a del usuario
        hikari:
          connection-test-query: SELECT 1 # Test de conexi칩n para PostgreSQL
          type: com.zaxxer.hikari.HikariDataSource
          minimum-idle: 3
          maximum-pool-size: 6
          auto-commit: true
          idle-timeout: 30000
          pool-name: GEOPSQLHIKARIPOOL # Nombre personalizado para el pool de PostgreSQL
          max-lifetime: 120000
          connection-timeout: 120000

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect # Habilitar para PostgreSQL
        show-sql: true
        hibernate:
            ddl-auto: none # Configura c칩mo Hibernate maneja el schema al iniciar
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            properties:
                hibernate:
                    jdbc:
                        format_sql: true
                        use_sql_comments: true

server:
    port: ${PORT:5007}
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

